---
name: 'check python package'

on:
  # FIXME: only disable for testing purposes
  # schedule:
  #   - cron: "0 0 * * 0"
  push:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      PY_PACKAGE_NAME: opencanary

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Get latest package version
        uses: Bruce17/ghaction-package-latest-version@v1
        id: pkg_version
        with:
          package: ${{ env.PY_PACKAGE_NAME }}
          language: python
          conditions: |
            pythonVersion: py3
            requiresPython: 3.7

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@1.0.0
