---
name: 'check python package'

on:
  # FIXME: only disable for testing purposes
  # schedule:
  #   - cron: "0 0 * * 0"
  push:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      PY_PACKAGE_NAME: opencanary

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Get latest package version
        # Disable fail fast on bash shell.
        # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
        shell: bash {0}
        run: |
          pip install yolk3k

          latest_version=`yolk -V $PY_PACKAGE_NAME | sed "s/$PY_PACKAGE_NAME\s*\(.*\)/\1/"`
          echo "latest version: $latest_version"

          # Set output parameters.
          echo ::set-output name=latest_version::${latest_version}

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@1.0.0
