name: CI

on:
  push:
    # tags:
    #   - '*'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Installing dependencies
        run: |
          sudo apt update && sudo apt install make -y
          git clone https://github.com/estesp/manifest-tool && cd manifest-tool && git checkout v0.9.0 && sudo make && sudo make install && cd .. && rm -Rf manifest-tool
          docker run --rm --privileged multiarch/qemu-user-static:register
          sudo apt install -y qemu qemu-user-static qemu-user binfmt-support

      - name: Build image
        run: make build

      - name: Publish image
        run: make publish latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_REPOSITORY }}
